### ISSUE TITLE
Can't find graphql config

### ISSUE THREAD

**Issue by pbassut** [graphcool/graphql-config#22]
I've defined both in the package.json like this:
```
"graphql": {
    "request": {
      "url": "https://api.graph.cool/relay/v1/cj2b3cy...3556gi9j5u"
    }
  },
```

and exported the environment variable like this:
export GRAPHQL_ENDPOINT="https://api.graph.cool/relay/v1/cj2b3cy...3556gi9j5u"

And I'm running `react-native run-ios`

Even with these both set, I receive the message saying it can't find the config.

Am I doing something wrong?

**Comment by pbassut** [comment]
Huh. I think I have to run npm run start to run the packager, but if I do `react-native run-ios` it won't work?

**Comment by marktani** [comment]
Could you post your full `package.json`?

**Comment by pbassut** [comment]
```json
{
  "name": "Lavapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "graphql": {
    "request": {
      "url": "https://api.graph.cool/relay/v1/cj2b3cyaz71ye013556gi9j5u"
    }
  },
  "dependencies": {
    "axios": "^0.15.3",
    "react": "15.4.2",
    "react-native": "0.41.2",
    "react-native-button": "^1.8.2",
    "react-native-calendar": "^0.11.0",
    "react-native-drawer": "^2.3.0",
    "react-native-elements": "^0.10.0",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-lock": "^0.4.0",
    "react-native-maps": "^0.13.0",
    "react-native-router-flux": "^3.38.1",
    "react-native-star-rating": "^1.0.7",
    "react-native-vector-icons": "^4.0.0",
    "react-relay": "^0.10.0",
    "recompose": "^0.23.1",
    "styled-components": "^1.4.5"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-plugin-react-relay": "^0.10.0",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "babel-preset-react-native": "1.9.1",
    "babel-relay-plugin": "^0.11.0",
    "jest": "18.1.0",
    "react-test-renderer": "15.4.2"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./app/assets/fonts"
    ]
  }
}

```

**Comment by pbassut** [comment]
But now my problem is different. 
I'm getting the transform error message:
![image](https://cloud.githubusercontent.com/assets/1500037/25774733/c96994ca-326b-11e7-8a5b-245ed5354a43.png)

But when I run `babel fileWithRelayQL.js` it correctly transpiles the QL calls to an IIFE calls.

**Comment by pbassut** [comment]
This is what worked for me: restarting my mac. So weird.
I got the answer here: http://stackoverflow.com/questions/39137302/react-native-relayql-unexpected-invocation-at-runtime

**Comment by pbassut** [comment]
@marktani just to be clear: it only picks up the config if I run `npm run start`, that is, run the packager manually. If I run `react-native run-ios` it won't pick it up. Correct?
