### ISSUE TITLE
Support alternative file extension for GQL files

### ISSUE THREAD

**Issue by marc-rutkowski** [graphcool/graphql-config#34]
Hello,

And thank you for this library!
It's nice to have a standardized way for handling configurations.

One little thing that bugged me today, is that I cannot directly use my existing `*.gql` schema files because they don't have the [required file extension](https://github.com/graphcool/graphql-config/blob/d162afaab16c444d26538e2c58695733c93c3e99/src/utils.ts#L103) :(

Maybe we could change this?

I can provide a PR with the basic change (add case '.gql') but no need for a PR I guess :)
Or with something more advanced if you have some ideas of improvements?

**Comment by schickling** [comment]
Thanks a lot for bringing this up!

@asiandrummer @sashko @IvanGoncharov  what do you think about supporting `.gql` files out of the box? I'm not too much of a fan fostering ambiguity between `.graphql` and `.gql` files.

**Comment by marc-rutkowski** [comment]
Instead of the switch on file extension, a very basic format detection can do the trick?
If JSON.parse() returns a SyntaxError, try to call directly valueToSchema() else call it with parsed JSON data.

**Comment by asiandrummer** [comment]
Where/how is `.gql` extension used? I'm also pessimistic with alternative file extensions, unless there's a clear need and a wide adoption for it.

**Comment by marc-rutkowski** [comment]
@asiandrummer you're right, the `.gql` extension doesn't seems really used, so I'll rename my files and close this :)
Thanks
