### ISSUE TITLE
Make graphql-js work with ES6 module

### ISSUE THREAD

**Issue by lvarayut** [graphcool/graphql-config#5]
The graphql-js option currently doesn't support ES6 module. If we exported a `schema.js` using ES6 syntax, as the following example, it will break:

```js
export default  new GraphQLSchema({
  query: QueryType
})
```

**Comment by schickling** [comment]
That's a good point. Do you have a good workaround in mind? Should we check if `obj.default` exists and use that instead?

**Comment by lvarayut** [comment]
I did exactly the same as you described. Here is how the workaround looks like:

```js
     case 'graphql-js':
       let schemaSource = require(resolve(config.file))
       schemaSource = schemaSource.default || schemaSource
       return graphql(schemaSource, introspectionQuery)
```

**Comment by schickling** [comment]
That looks good to me. Feel free to merge it in :)
