### ISSUE TITLE
Support loading unwrapped schema.json file

### ISSUE THREAD

**Issue by stephen** [graphcool/graphql-config#51]
It would be nice to support loading schema.json files that do not have the `{ "data": {}, "errors": [] }` wrapper.

[Other libraries](https://github.com/apollographql/apollo-codegen/blob/39c2f8e901f9211f4ab57eadd656c6bad24b6a8a/src/loading.ts#L29) support this by only passing `introspectionResult.data` if it exists.

While I do think this makes things a little more ambiguous, it seems nice to either implicitly support these files, or explicitly allow a user-configurable option to load non-wrapped introspection schemas. I would be curious to see if there is a good use case for wanting to write an error-result to a `schema.json` in the first place.

wdyt? I would be happy to send a PR for either.

**Comment by schickling** [comment]
Agree, let's move forward with this!

**Comment by stephen** [comment]
#53
