### ISSUE TITLE
Add `package.json` `engines` field

### ISSUE THREAD

**Issue by jaydenseric** [graphcool/graphql-config#76]
It is best practice for packages to contain a [`package.json` `engines` field](https://docs.npmjs.com/files/package.json#engines). What versions of Node.js does this package support?

See https://github.com/apollographql/eslint-plugin-graphql/issues/105#issuecomment-359326335.

**Comment by voxpelli** [comment]
👍 I totally agree that this should be added – eg. enables automatic checking of compatibility, something I do through my: http://github.com/voxpelli/node-installed-check/#options

**Comment by schickling** [comment]
Great suggestion! Would you mind opening a PR @jaydenseric?

**Comment by jaydenseric** [comment]
@schickling It is unclear what the oldest version of Node.js that works with this package is; can you shed some light? It would likely be a pretty specific version (not just a major), depending on what ES features are used; dependencies, etc.

Once you work it out I also suggest [configuring Travis](https://github.com/graphcool/graphql-config/blob/master/.travis.yml#L5) to run on the exact lowest supported version in `engines` and the latest stable ([using `node` keyword](https://github.com/jaydenseric/apollo-upload-server/blob/master/.travis.yml#L3)) to test both ends of a `>=` range.

I don't use TypeScript, so I don't know best practices with that but I [configure `babel-preset-env` to read directly from `engines`](https://github.com/jaydenseric/apollo-upload-server/blob/master/.babelrc.js#L10) for the transpilation target so no unnecessary transpilation, runtimes or polyfills are distributed. This is critical for browser code, but still good for Node.js-only packages. Side note: Babel v7 can handle TypeScript now with [`babel-preset-typescript`](https://github.com/babel/babel/tree/master/packages/babel-preset-typescript).

**Comment by kbrandwijk** [comment]
I'm gonna guesstimate here, but as our typescript config targets `es5` explicitly, and node is 100% es5 compatible since v0.10, I think that's the minimal supported version.

**Comment by schickling** [comment]
I remember @jnwng was also looking into this and was even about to open a PR to backporting a few features. Can you chime in here @jnwng? :)

**Comment by voxpelli** [comment]
Made a stab at a PR: https://github.com/graphcool/graphql-config/pull/78

The Node.js 8.x engine requirement should probably be seen as a bug? An engine requirement of eg. 4.x or 6.x would make most sense

**Comment by jnwng** [comment]
Node 6 which is still in active LTS is what we should aim for here. 

Unfortunately, TypeScript does not add polyfills for certain environments, so even though the output is ES5, it still won’t actually be compatible with the Node environment. I think the course of action here is to add a Babel step using `babel-preset-env` following the TypeScript step so we can continue using new constructs without having to special case each one. 

Additionally it’s worth adding environment checks in CI to confirm that these work. See https://github.com/jnwng/graphql-import/pull/1

What do you all think?
