### ISSUE TITLE
Support configuring via typeDefinitions

### ISSUE THREAD

**Issue by tonyxiao** [graphcool/graphql-config#8]
See example here

https://github.com/tonyxiao/eslint-plugin-graphql/blob/master/test/updateSchemaJson.js#L5-L11

Basically allow people to import a package which represents their server and generate a schema based on their server code. Could be either the result of `graphql.buildASTSchema`, a string which contains graphQL schema type definitions, or path to a `.graphql` file.

**Comment by schickling** [comment]
Isn't [this](https://github.com/graphcool/graphql-config/tree/master/tests/package_graphql_js) already what you're looking for?

**Comment by tonyxiao** [comment]
Hmm I'm talking about this line in particular

```
var schema = graphql.buildASTSchema(graphql.parse(typeDefinition));
```

**Comment by schickling** [comment]
So any ideas how we can enable this with graphql-config without bloating it up too much?

**Comment by tonyxiao** [comment]
The advantage of configuring via an actual schema / type definitions is that you don't need a running server somewhere and you can make sure the test you are running is always testing against the version of schema that you wrote the code for (So going back to an old commit, test wont be magically broken because API server has changed). 

I imagine you have to provide an import path for us to find the module which contains the `AST` schema. So maybe an additional option like so?

`.graphqlrc`
```json
{
  "schema": "yourpackage/schema"
}
```
`yourpackage/schema.js`
```
import graphql from 'graphql'

const typeDefinition = `
...
`
export default graphql.buildASTSchema(graphql.parse(typeDefinition));
```

**Comment by tonyxiao** [comment]
Oh wait, that's just what you were talking about earlier... 

https://github.com/graphcool/graphql-config/blob/master/README.md#use-local-schema-file-graphqljs

I guess I totally misread for some reason. Closing issue then. :)
